# Generated by Django 4.2.5 on 2023-09-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_subscription_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='prevent_self_follow',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
    ]
