# Generated by Django 3.2.3 on 2023-11-23 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_subcribed_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Invalid username.', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
