# Generated by Django 4.2.5 on 2023-10-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_pub_date'),
        ('recipes', '0012_recipe_pub_date'),
    ]

    operations = [
    ]
