# Generated by Django 4.2.5 on 2023-10-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_subscription_prevent_self_follow'),
        ('recipes', '0013_merge_0010_recipe_pub_date_0012_recipe_pub_date'),
    ]

    operations = [
    ]
